name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python3
        with:
          # Sematic version range syntax or specific version
          python-version: '3.10'
          architecture: 'x64'
          # You can test your matrix by printing current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"